apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretnames.authpassword }}
  namespace: {{ .Values.global.namespace}}
type: Opaque
stringData:
  password: {{ .Values.global.kafkaserver.password}}
