apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.assumerolename }}/{{ .Values.global.kafkaconnectname }}-connect
  creationTimestamp: "2020-06-17T21:48:25Z"
  labels:
    app.kubernetes.io/instance: {{ .Values.global.kafkaconnectname }}
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka-connect
    app.kubernetes.io/part-of: strimzi-{{ .Values.global.kafkaconnectname }}
    strimzi.io/cluster: {{ .Values.global.kafkaconnectname }}
    strimzi.io/kind: KafkaConnect
    strimzi.io/name: strimzi
  name: {{ .Values.global.kafkaconnectname }}-connect
  namespace: {{ .Values.global.namespace}}
  resourceVersion: "855936"
  selfLink: /api/v1/namespaces/default/serviceaccounts/{{ .Values.global.kafkaconnectname }}-connect
  uid: 24bdb5d3-1d43-4bf6-b883-b275b0f5397e
secrets:
- name: {{ .Values.global.kafkaconnectname }}-connect-token-glprh
