apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretnames.hebcertificate }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  cert.crt: {{ .Values.global.kafkaserver.tlscert}}
